name: Cypress Integration Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'
